### ISSUE TITLE
[APP SUBMITTED]: HTTPSConnectionPool(host='cdn.pymedusa.com', port=443): Max retries exceeded with url: /sb_network_timezones/network_timezones.txt (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb40f960c>: Failed to establish a new connection: [Errno -2] Name or service not known',))

### ISSUE THREAD

**Issue by duramato** [pymedusa/SickRage#835] opened 2016-07-29 20:05 UTC
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **split-parsing**
Commit: PyMedusa/SickRage@77825a8ced266a0e402eee57cd381fa63adf0219
Link to Log: https://gist.github.com/b58f83c05d1c3a287043fca82dbc9500
### ERROR
```
DAILYSEARCHER :: [77825a8] Exception generated in thread DAILYSEARCHER: error HTTPSConnectionPool(host='cdn.pymedusa.com', port=443): Max retries exceeded with url: /sb_network_timezones/network_timezones.txt (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb40f960c>: Failed to establish a new connection: [Errno -2] Name or service not known',))
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/scheduler.py", line 106, in run
    self.action.run(self.force)
  File "/home/home/SickRage/sickbeard/dailysearcher.py", line 75, in run
    update_network_dict()
  File "/home/home/SickRage/sickbeard/network_timezones.py", line 47, in update_network_dict
    url_data = helpers.getURL(url, session=helpers.make_session(), returns='text')
  File "/home/home/SickRage/sickbeard/helpers.py", line 1424, in getURL
    verify=verify)
  File "/home/home/SickRage/lib/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/home/SickRage/lib/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/home/home/SickRage/lib/cachecontrol/adapter.py", line 46, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/home/home/SickRage/lib/requests/adapters.py", line 467, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='cdn.pymedusa.com', port=443): Max retries exceeded with url: /sb_network_timezones/network_timezones.txt (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb40f960c>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment] 2016-07-29 20:10
@medariox another exception catch that was removed

**Comment by medariox** [comment] 2016-07-30 12:32
What's the issue? We can add it back, right? That's what testing is for.

**Comment by fernandog** [comment] 2016-07-30 12:34
@medariox not sure which one needs to add back

**Comment by medariox** [comment] 2016-07-30 12:37
```requests.exceptions.ConnectionError```

**Comment by fernandog** [comment] 2016-07-30 12:41
but we already catch requests.exceptions:

Isn't the same? Need to catch all `requests.exceptions` then and not only connection error

```python
    try:
        resp.raise_for_status()
    except requests.RequestException as e:
        logger.log(u'Error requesting url {resp.url}. Error: {msg}'.format(resp=resp, msg=ex(e)), logger.DEBUG)
```

**Comment by medariox** [comment] 2016-07-30 12:46
I think the problem is that it should be
```
requests.exceptions.RequestException
```

**Comment by medariox** [comment] 2016-07-30 12:53
Btw SocketTimeout is handled by requests.exceptions.Timeout in Requests.
So we need to remove that again.

**Comment by fernandog** [comment] 2016-07-30 13:05
can you commit that? using phone

**Comment by medariox** [comment] 2016-07-30 13:27
Done. Closing

**Closed by medariox** 2016-07-30 13:27 UTC
