### ISSUE TITLE
[APP SUBMITTED]: 17:43:29 ERROR::FINDSUBTITLES :: [89a4599] No show id found for u'Misfit Garage' ({'year': 2014})
None

### ISSUE THREAD

**Issue by duramato** [pymedusa/SickRage#300] opened 2016-04-07 16:46 UTC
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: UTF-8
Branch: **develop**
Commit: PyMedusa/SickRage@89a459923cfb2020bc32aab80527bc8a263731d5
No Log available with ERRORS:
### ERROR
```
17:43:29 ERROR::FINDSUBTITLES :: [89a4599] No show id found for u'Misfit Garage' ({'year': 2014})
None
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by ratoaq2** [comment] 2016-04-07 18:31
Duplicate of #299
Only different series name

**Closed by ratoaq2** 2016-04-07 18:31 UTC
Labels: duplicate
