### ISSUE TITLE
[APP SUBMITTED]: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by duramato** [pymedusa/SickRage#362] opened 2016-04-11 14:09 UTC
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **develop**
Commit: PyMedusa/SickRage@0f7b155d748fead090706f6d22c529b9a5736740
No Log available with ERRORS:
### ERROR
```
SEARCHQUEUE-BACKLOG-272644 :: [HD4Free] :: [0f7b155] Unknown exception while searching HD4Free. Error: "'NoneType' object has no attribute 'get'"
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/search.py", line 531, in searchProviders
    forced_search, downCurQuality, manual_search)
  File "/home/home/SickRage/sickrage/providers/GenericProvider.py", line 149, in find_search_results
    items_list += self.search(search_string, ep_obj=episode)
  File "/home/home/SickRage/sickbeard/providers/hd4free.py", line 83, in search
    error = jdata.get('error')
AttributeError: 'NoneType' object has no attribute 'get'
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment] 2016-04-11 14:10
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **develop**
Commit: PyMedusa/SickRage@0f7b155d748fead090706f6d22c529b9a5736740
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-REFRESH :: [0f7b155] 110381: Could not refresh subtitles
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/tv.py", line 445, in loadEpisodesFromDir
    curEpisode.refreshSubtitles()
  File "/home/home/SickRage/sickbeard/tv.py", line 1411, in refreshSubtitles
    self.saveToDB()
  File "/home/home/SickRage/sickbeard/tv.py", line 1951, in saveToDB
    "subtitles": ",".join(self.subtitles),
TypeError
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment] 2016-04-11 14:10
### INFO
Python Version: **2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]**
Operating System: **Linux-3.19.0-56-generic-i686-with-Ubuntu-14.04-trusty**
Locale: None
Branch: **develop**
Commit: PyMedusa/SickRage@0f7b155d748fead090706f6d22c529b9a5736740
No Log available with ERRORS:
### ERROR
```
SHOWQUEUE-REFRESH :: [0f7b155] Error while updating database: TypeError('',)
Traceback (most recent call last):
  File "/home/home/SickRage/sickbeard/tv.py", line 1901, in get_sql
    [self.indexerid, self.indexer, self.name, self.description, ",".join(self.subtitles),
TypeError
```
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment] 2016-04-11 14:23
@ratoaq2 maybe in this PR, if current_subtitles = '' we need to set it to None

https://github.com/pymedusa/SickRage/pull/359

**Comment by fernandog** [comment] 2016-04-11 14:23
@duramato about this error, you should be able to fix it:

```
    error = jdata.get('error')
AttributeError: 'NoneType' object has no attribute 'get
```

**Comment by duramato** [comment] 2016-04-11 14:56
`subtitles_languages = "pob,por,eng"`

**Comment by ratoaq2** [comment] 2016-04-11 17:10
current_subtitles cannot be '', it's a list. It will be []

**Comment by fernandog** [comment] 2016-04-12 15:39
cant reproduce the error. closing

**Comment by fernandog** [comment] 2016-04-12 15:40
@duramato are you going to PR hd4free fix?

**Closed by fernandog** 2016-04-12 15:39 UTC
