### ISSUE TITLE
How upgrade from sickrage in Qnap NAS ?

### ISSUE THREAD

**Issue by felipesalomao** [pymedusa/SickRage#481] opened 2016-04-26 03:09 UTC
Hi, how could i upgrade ? I was thinking about git clone commands on putty, then ovewrite original sickrage files.. Could tell exactly witch commands i need type ? I already did something like it when upgraded from sickbeard to sickrage, but dont know exactly what commands i need type.. Thanks

**Comment by labrys** [comment] 2016-04-26 09:06
I'm not familiar with Qnap NAS's, however you should be able to upgrade by shutting down sickrage, editing the Config.ini to change the upstream URL to 'https://github.com/pymedusa/sickrage' and deleting the commit hash.  As always make sure you backup your database first.  Easiest way is from the SickRage UI.

**Comment by felipesalomao** [comment] 2016-04-26 09:08
Hi, where is located config.ini? On same folder that sick rage is
installed? Or some another Linux location.. How delete commit hash? Thank
you

Em terça-feira, 26 de abril de 2016, Labrys of Knossos <
notifications@github.com> escreveu:

**Comment by labrys** [comment] 2016-04-26 09:12
The commit hash is another line entry in the config file... You can find the location of your config.ini from the Help & Info page within sickrage.  Change the lines to the following:
```
git_remote_url = https://github.com/pymedusa/SickRage.git
cur_commit_hash = ""
```

**Comment by felipesalomao** [comment] 2016-04-26 09:31
I located configuration file. Shut down sick rage. Then updated address in config file and started again sick rage. It upgraded, but had some kind of error (see in putty picture). But anyway it started old sick rage version and config file was restored with old sick rage address.. Was not able to find hash on config file. 

See both screens hot in attachment. 

![image](https://cloud.githubusercontent.com/assets/2954256/14813521/6f8c9512-0b78-11e6-84ac-6f8affcb9cad.jpeg)
![Uploading image.jpeg…]()

**Comment by p0psicles** [comment] 2016-04-26 10:01
That looks good. It has fetched all medusa branches. Per default you will checkout the master branch. The commit of this branch should be https://github.com/pymedusa/SickRage/commit/55af59244f853c38812832343f2209fec59bc8de. That should also show on the Help & Info page.

If you really want see some new functionality you could give develop a try. But this will make modifications, there's no going back to master, without moving forward with an empty db.

**Comment by felipesalomao** [comment] 2016-04-26 10:06
Em terça-feira, 26 de abril de 2016, p0ps <notifications@github.com>
escreveu:

**Comment by felipesalomao** [comment] 2016-04-26 10:08
But I really don't know how make that. In command line it show that was unable to get my email address, then update fails and old sick rage git URL is restored.. What exactly I should make different? 
I doesn't know too much about code..

**Comment by p0psicles** [comment] 2016-04-26 12:08
Else try this first? https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup#Your-Identity

**Comment by felipesalomao** [comment] 2016-04-26 12:16
Added this commands to register name and email. Not got anymore this error. But now it show another error. 
![image](https://cloud.githubusercontent.com/assets/2954256/14817755/87378fca-0b8f-11e6-8254-9b2297e91883.jpeg)

**Comment by p0psicles** [comment] 2016-04-26 14:36
Make sure your config still points to the pymedusa fork. Then run these commands:
git fetch --all
git reset --hard HEAD

That should fix it.

**Comment by felipesalomao** [comment] 2016-04-27 20:19
Was able to install it following: 
http://forum.qnap.com/viewtopic.php?f=223&t=118366&sid=6be1a4821d2d3e7f13ce747100a434ca

Aftr instaled, it opened webpage to select witch repo i want, then added github.com/pymedusa/SickRage.git in custom and clicked custom..

**Comment by felipesalomao** [comment] 2016-04-27 20:20
But had some error to switch to develop branch, i explain better  here: https://github.com/pymedusa/SickRage/issues/498

**Comment by OmgImAlexis** [comment] 2016-10-05 04:03
Closing this as the issue is over 4 months old.

**Closed by OmgImAlexis** 2016-10-05 04:03 UTC
Labels: question
